# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have a high-level overview of PCA, as well as some of the details of the algorithm itself, it's time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the data

- Import the data stored in the file `'foodusa.csv'` (set `index_col=0`)
- Print the first five rows of the DataFrame

In [3]:
import pandas as pd
data = pd.read_csv('foodusa.csv')

data.head()

        City  Bread  Burger  Milk  Oranges  Tomatoes
0    ATLANTA   24.5    94.5  73.9     80.1      41.6
1  BALTIMORE   26.5    91.0  67.5     74.6      53.3
2     BOSTON   29.7   100.8  61.4    104.0      59.6
3    BUFFALO   22.8    86.6  65.3    118.4      51.2
4    CHICAGO   26.7    86.7  62.7    105.9      51.2

In [4]:
import pandas as pd
data = pd.read_csv('foodusa.csv', index_col=0)

data.head()

           Bread  Burger  Milk  Oranges  Tomatoes
City
ATLANTA     24.5    94.5  73.9     80.1      41.6
BALTIMORE   26.5    91.0  67.5     74.6      53.3
BOSTON      29.7   100.8  61.4    104.0      59.6
BUFFALO     22.8    86.6  65.3    118.4      51.2
CHICAGO     26.7    86.7  62.7    105.9      51.2

## Normalize the data

Next, normalize your data by subtracting the mean from each of the columns.

In [5]:
data = data - data.mean()
data.head()

              Bread    Burger       Milk    Oranges   Tomatoes
City
ATLANTA   -0.791304  2.643478  11.604348 -22.891304  -7.165217
BALTIMORE  1.208696 -0.856522   5.204348 -28.391304   4.534783
BOSTON     4.408696  8.943478  -0.895652   1.008696  10.834783
BUFFALO   -2.491304 -5.256522   3.004348  15.408696   2.434783
CHICAGO    1.408696 -5.156522   0.404348   2.908696   2.434783

## Calculate the covariance matrix

The next step is to calculate the covariance matrix for your normalized data.

In [7]:
import numpy as np
cov_mat = np.cov(data)
cov_mat

array([[ 1.65628796e+02,  1.53459426e+02, -2.57203025e+00,
        -7.59348781e+01, -2.18608129e+01,  4.07244915e+01,
        -7.98600520e+01, -7.62231172e+01, -7.46028563e+01,
        -6.99662911e+01, -1.49866824e+01,  2.32682958e+01,
         8.37080784e+01, -8.62530737e+01, -5.52929650e+01,
         1.10157306e+01,  2.85812524e+01, -7.15072259e+01,
        -6.07858346e+01,  3.09254045e+01, -8.54887807e+00,
         3.79245132e+01,  1.23158709e+02],
       [ 1.53459426e+02,  1.97233057e+02,  2.56101002e+01,
        -9.03397476e+01, -1.39991824e+01,  2.60341219e+01,
        -8.00284216e+01, -1.12873487e+02, -5.81142259e+01,
        -1.05876161e+02, -4.49475520e+01,  7.32042628e+00,
         9.08802089e+01, -7.04269433e+01, -3.82768346e+01,
         2.98243611e+01,  6.64678828e+01, -8.71905955e+01,
        -8.15837042e+01,  1.84315350e+01, -1.84792476e+01,
         5.16286437e+01,  1.35246339e+02],
       [-2.57203025e+00,  2.56101002e+01,  2.51341437e+01,
        -2.06072042e+01, -5.16863894e+00,  8.24566541e+00,
         8.49621928e-01, -3.13169433e+01,  1.65203176e+01,
        -2.16436172e+01, -3.09195085e+01, -1.38755302e+01,
         1.00342524e+01,  9.67260019e+00,  1.53802089e+01,
         2.98014045e+01,  1.83309263e+01, -6.25505198e+00,
        -1.29196607e+01, -1.08814216e+01, -8.92520416e+00,
        -8.03581285e+00,  1.35413828e+01],
       [-7.59348781e+01, -9.03397476e+01, -2.06072042e+01,
         6.29744480e+01,  1.75795132e+01, -3.25281824e+01,
         3.36277741e+01,  6.30692089e+01,  1.81354698e+01,
         6.49280350e+01,  3.88361437e+01, -1.34187807e+00,
        -6.20020955e+01,  3.79302524e+01,  8.73786106e+00,
        -3.06534433e+01, -1.59959216e+01,  3.67431002e+01,
         3.60739915e+01, -1.66787694e+01,  4.22094802e+00,
        -6.42516068e+00, -7.03494650e+01],
       [-2.18608129e+01, -1.39991824e+01, -5.16863894e+00,
         1.75795132e+01,  1.05815784e+01, -1.87071172e+01,
         7.56733932e+00,  1.41352741e+01,  3.18353497e+00,
         7.04810019e+00,  1.10007089e+01,  1.71687146e-01,
        -1.40485302e+01,  1.00033176e+01,  2.20842628e+00,
        -1.50428781e+01,  2.63864367e+00,  4.42516541e+00,
         5.83755671e+00, -1.81320416e+00,  2.41451323e+00,
         9.53690454e+00, -1.76918998e+01],
       [ 4.07244915e+01,  2.60341219e+01,  8.24566541e+00,
        -3.25281824e+01, -1.87071172e+01,  3.33321871e+01,
        -1.40863563e+01, -2.50654216e+01, -6.92316068e+00,
        -1.52245955e+01, -1.91729868e+01,  8.55991493e-01,
         2.76457741e+01, -1.99083781e+01, -4.61326938e+00,
         2.50704263e+01, -6.22505198e+00, -8.61853025e+00,
        -1.04231389e+01,  5.78010019e+00, -2.92118242e+00,
        -1.57967911e+01,  3.25254045e+01],
       [-7.98600520e+01, -8.00284216e+01,  8.49621928e-01,
         3.36277741e+01,  7.56733932e+00, -1.40863563e+01,
         4.04581002e+01,  3.83960350e+01,  3.76142958e+01,
         3.34238611e+01,  5.68396975e+00, -1.05075520e+01,
        -3.69027694e+01,  3.98890784e+01,  2.81291871e+01,
        -3.32711720e+00, -2.12655955e+01,  3.76184263e+01,
         3.23883176e+01, -1.18599433e+01,  6.41027410e+00,
        -2.39998346e+01, -6.02186389e+01],
       [-7.62231172e+01, -1.12873487e+02, -3.13169433e+01,
         6.30692089e+01,  1.41352741e+01, -2.50654216e+01,
         3.83960350e+01,  7.87969698e+01,  1.57892306e+01,
         6.74627958e+01,  4.68144045e+01,  6.28338280e+00,
        -5.50068346e+01,  2.95090132e+01,  7.05412193e+00,
        -4.00671824e+01, -4.10926607e+01,  4.56338611e+01,
         4.81542524e+01, -2.49250851e+00,  1.49012089e+01,
        -1.40493998e+01, -7.78122042e+01],
       [-7.46028563e+01, -5.81142259e+01,  1.65203176e+01,
         1.81354698e+01,  3.18353497e+00, -6.92316068e+00,
         3.76142958e+01,  1.57892306e+01,  4.48934915e+01,
         1.85840567e+01, -1.40823346e+01, -1.84793563e+01,
        -2.82795737e+01,  4.28332741e+01,  3.52833828e+01,
         1.63820784e+01, -8.18439981e+00,  3.09971219e+01,
         2.18065132e+01, -1.83982476e+01, -1.46530246e-01,
        -2.80211389e+01, -4.67909433e+01],
       [-6.99662911e+01, -1.05876161e+02, -2.16436172e+01,
         6.49280350e+01,  7.04810019e+00, -1.52245955e+01,
         3.34238611e+01,  6.74627958e+01,  1.85840567e+01,
         9.05916219e+01,  4.01347306e+01, -2.96579112e+00,
        -7.23060085e+01,  3.92963393e+01,  5.89894802e+00,
        -1.71848563e+01, -2.28498346e+01,  4.50166871e+01,
         4.08175784e+01, -2.67726824e+01, -1.99296503e+00,
        -2.56115737e+01, -7.08083781e+01],
       [-1.49866824e+01, -4.49475520e+01, -3.09195085e+01,
         3.88361437e+01,  1.10007089e+01, -1.91729868e+01,
         5.68396975e+00,  4.68144045e+01, -1.40823346e+01,
         4.01347306e+01,  4.27348393e+01,  1.35158176e+01,
        -2.85243998e+01,  2.94948015e-01, -1.52424433e+01,
        -3.88762476e+01, -1.79447259e+01,  1.35792958e+01,
         2.01616871e+01,  4.41092628e+00,  8.19114367e+00,
         9.65353497e+00, -3.03152694e+01],
       [ 2.32682958e+01,  7.32042628e+00, -1.38755302e+01,
        -1.34187807e+00,  1.71687146e-01,  8.55991493e-01,
        -1.05075520e+01,  6.28338280e+00, -1.84793563e+01,
        -2.96579112e+00,  1.35158176e+01,  1.13497958e+01,
         9.88457845e+00, -1.82870737e+01, -1.46694650e+01,
        -1.59632694e+01, -8.43624764e+00, -6.48722590e+00,
        -7.96834594e-01,  1.35564045e+01,  5.92262193e+00,
         1.02095132e+01,  9.47170888e+00],
       [ 8.37080784e+01,  9.08802089e+01,  1.00342524e+01,
        -6.20020955e+01, -1.40485302e+01,  2.76457741e+01,
        -3.69027694e+01, -5.50068346e+01, -2.82795737e+01,
        -7.23060085e+01, -2.85243998e+01,  9.88457845e+00,
         7.02993611e+01, -4.90022911e+01, -1.58646824e+01,
         1.39065132e+01,  7.10853497e+00, -3.96174433e+01,
        -3.38870520e+01,  3.03311871e+01,  3.86740454e+00,
         1.65092958e+01,  7.12664915e+01],
       [-8.62530737e+01, -7.04269433e+01,  9.67260019e+00,
         3.79302524e+01,  1.00033176e+01, -1.99083781e+01,
         3.98890784e+01,  2.95090132e+01,  4.28332741e+01,
         3.92963393e+01,  2.94948015e-01, -1.82870737e+01,
        -4.90022911e+01,  5.13730567e+01,  3.13356654e+01,
         6.03436106e+00, -1.92461720e+00,  3.46044045e+01,
         2.56162958e+01, -2.73234650e+01, -3.49674764e+00,
        -2.20213563e+01, -5.97486607e+01],
       [-5.52929650e+01, -3.82768346e+01,  1.53802089e+01,
         8.73786106e+00,  2.20842628e+00, -4.61326938e+00,
         2.81291871e+01,  7.05412193e+00,  3.52833828e+01,
         5.89894802e+00, -1.52424433e+01, -1.46694650e+01,
        -1.58646824e+01,  3.13356654e+01,  2.86832741e+01,
         1.43694698e+01, -5.28950851e+00,  2.13945132e+01,
         1.44339045e+01, -1.17758563e+01,  6.93361059e-01,
        -2.03487476e+01, -3.22285520e+01],
       [ 1.10157306e+01,  2.98243611e+01,  2.98014045e+01,
        -3.06534433e+01, -1.50428781e+01,  2.50704263e+01,
        -3.32711720e+00, -4.00671824e+01,  1.63820784e+01,
        -1.71848563e+01, -3.88762476e+01, -1.59632694e+01,
         1.39065132e+01,  6.03436106e+00,  1.43694698e+01,
         4.55556654e+01,  1.67191871e+01, -6.21929112e+00,
        -1.56273998e+01, -1.52371607e+01, -1.37079433e+01,
        -2.07550520e+01,  2.39826437e+01],
       [ 2.85812524e+01,  6.64678828e+01,  1.83309263e+01,
        -1.59959216e+01,  2.63864367e+00, -6.22505198e+00,
        -2.12655955e+01, -4.10926607e+01, -8.18439981e+00,
        -2.28498346e+01, -1.79447259e+01, -8.43624764e+00,
         7.10853497e+00, -1.92461720e+00, -5.28950851e+00,
         1.67191871e+01,  4.59107089e+01, -2.81702694e+01,
        -3.11103781e+01, -1.51986389e+01, -1.74134216e+01,
         2.07964698e+01,  3.45476654e+01],
       [-7.15072259e+01, -8.71905955e+01, -6.25505198e+00,
         3.67431002e+01,  4.42516541e+00, -8.61853025e+00,
         3.76184263e+01,  4.56338611e+01,  3.09971219e+01,
         4.50166871e+01,  1.35792958e+01, -6.48722590e+00,
        -3.96174433e+01,  3.46044045e+01,  2.13945132e+01,
        -6.21929112e+00, -2.81702694e+01,  3.98287524e+01,
         3.55761437e+01, -1.08571172e+01,  6.70560019e+00,
        -2.74295085e+01, -5.97708129e+01],
       [-6.07858346e+01, -8.15837042e+01, -1.29196607e+01,
         3.60739915e+01,  5.83755671e+00, -1.04231389e+01,
         3.23883176e+01,  4.81542524e+01,  2.18065132e+01,
         4.08175784e+01,  2.01616871e+01, -7.96834594e-01,
        -3.38870520e+01,  2.56162958e+01,  1.44339045e+01,
        -1.56273998e+01, -3.11103781e+01,  3.55761437e+01,
         3.44965350e+01, -3.31272590e+00,  1.01434915e+01,
        -2.00046172e+01, -5.50549216e+01],
       [ 3.09254045e+01,  1.84315350e+01, -1.08814216e+01,
        -1.66787694e+01, -1.81320416e+00,  5.78010019e+00,
        -1.18599433e+01, -2.49250851e+00, -1.83982476e+01,
        -2.67726824e+01,  4.41092628e+00,  1.35564045e+01,
         3.03311871e+01, -2.73234650e+01, -1.17758563e+01,
        -1.52371607e+01, -1.51986389e+01, -1.08571172e+01,
        -3.31272590e+00,  2.65650132e+01,  1.25442306e+01,
         1.16046219e+01,  1.84523176e+01],
       [-8.54887807e+00, -1.84792476e+01, -8.92520416e+00,
         4.22094802e+00,  2.41451323e+00, -2.92118242e+00,
         6.41027410e+00,  1.49012089e+01, -1.46530246e-01,
        -1.99296503e+00,  8.19114367e+00,  5.92262193e+00,
         3.86740454e+00, -3.49674764e+00,  6.93361059e-01,
        -1.37079433e+01, -1.74134216e+01,  6.70560019e+00,
         1.01434915e+01,  1.25442306e+01,  1.03304480e+01,
         2.57339319e-01, -1.09704650e+01],
       [ 3.79245132e+01,  5.16286437e+01, -8.03581285e+00,
        -6.42516068e+00,  9.53690454e+00, -1.57967911e+01,
        -2.39998346e+01, -1.40493998e+01, -2.80211389e+01,
        -2.56115737e+01,  9.65353497e+00,  1.02095132e+01,
         1.65092958e+01, -2.20213563e+01, -2.03487476e+01,
        -2.07550520e+01,  2.07964698e+01, -2.74295085e+01,
        -2.00046172e+01,  1.16046219e+01,  2.57339319e-01,
         3.67072306e+01,  2.76709263e+01],
       [ 1.23158709e+02,  1.35246339e+02,  1.35413828e+01,
        -7.03494650e+01, -1.76918998e+01,  3.25254045e+01,
        -6.02186389e+01, -7.78122042e+01, -4.67909433e+01,
        -7.08083781e+01, -3.03152694e+01,  9.47170888e+00,
         7.12664915e+01, -5.97486607e+01, -3.22285520e+01,
         2.39826437e+01,  3.45476654e+01, -5.97708129e+01,
        -5.50549216e+01,  1.84523176e+01, -1.09704650e+01,
         2.76709263e+01,  1.01896622e+02]])

In [9]:
cov_mat = data.cov()
cov_mat

              Bread     Burger       Milk     Oranges   Tomatoes
Bread      6.284466  12.910968   5.719051    1.310375   7.285138
Burger    12.910968  57.077115  17.507530   22.691877  36.294783
Milk       5.719051  17.507530  48.305889   -0.275040  13.443478
Oranges    1.310375  22.691877  -0.275040  202.756285  38.762411
Tomatoes   7.285138  36.294783  13.443478   38.762411  57.800553

## Calculate the eigenvectors

Next, calculate the eigenvectors and eigenvalues for your covariance matrix.

In [10]:
import numpy as np
eig_values, eig_vectors = np.linalg.eig(cov_mat)

## Sort the eigenvectors 

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues to determine primary components!

In [11]:
# Get the index values of the sorted eigenvalues
e_indices = np.argsort(eig_values)[::-1]

# Sort 
eigenvectors_sorted = eig_vectors[:,e_indices]
eigenvectors_sorted

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the data

Finally, reproject the dataset using your eigenvectors. Reproject this dataset down to 2 dimensions.

In [17]:
transformed = eigenvectors_sorted[:2].dot(data.T).T
pd.DataFrame(transformed, columns=['PC1', 'PC2'])

          PC1        PC2
0   11.106367  14.731349
1    1.219003  21.449894
2  -12.293656  -4.732865
3   -4.274105  -4.957463
4   -2.085702   1.770715
5    2.023230  -4.831307
6    0.765140  -5.782419
7    5.019903  -7.083027
8   -5.289636  -7.185603
9  -20.294912 -21.807328
10   6.659848   1.940003
11   6.311287   2.489291
12  14.121272  10.530503
13  -6.303608  -4.258464
14  -2.701193  -4.221704
15 -17.391014 -11.469437
16 -11.519778   7.502795
17  -3.850462 -12.114004
18   0.027427  -9.578903
19  16.089301   7.155854
20   7.924954   0.766674
21   8.407963  16.303338
22   6.328374  13.382107

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further applications of PCA.